name: build-push
on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
      registry:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Registry login
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Calculate metadata
        id: meta
        run: |
          img_name=${{ inputs.registry }}/${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
          bumped_tag=${{ inputs.tag }}
          if [ ! -z $bumped_tag ]; then
            img_tag=$bumped_tag
          elif [ $GITHUB_REF_TYPE = "tag" ]; then
            img_tag=$GITHUB_REF_NAME
          else
            img_tag=$(echo ${GITHUB_REF_NAME} | tr -s '[:punct:]' '-')-${GITHUB_RUN_ATTEMPT}-${GITHUB_SHA:0:8}
          fi
          echo "::set-output name=name::$img_name"
          echo "::set-output name=tag::$img_tag"
          echo "New image name: $img_name:$img_tag"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.name }}:${{ steps.meta.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
